https.port: "8082"
http.port: "8081"
host: "0.0.0.0"
authorization: "testAuthorization"
applicationKey: "testKey"
tls.keySecret: "linear_xglinear_mule_app"
tls.keyStoreSecret: "linear_xglinear_mule_app"

api_id : "111"

proposalLineItemCall:
  maxConCurrency: "1"

sample:
  host: "0.0.0.0"
  port: "443"

GAM:
  host: "https://media-gam-integration-sapi.us-e2.cloudhub.io"
  port: "443"
  basepath: "/api"
  url:
    proposals: "/api/proposal"
    performProposalAction: "/api/proposal/action"
    proposalLineItems: "/api/proposal/lineItems"
    proposalStatus: "/proposal/statusQuery"


XG:
  host: "https://media-gam-integration-sapi.us-e2.cloudhub.io"
  port: "443"
  url:
    proposals: "/api/proposal"
    performProposalAction: "/api/proposal/action"
    proposalLineItems: "/api/proposal/lines"

client_id : "random123"
client_secret: "random123"

flag:
  validHttpStatusCodes: "false"

forwardResponse :
  flag : "false"
  queue : "converged-media-process-queue-dummy"
  url : "https://mq-us-east-1.anypoint.mulesoft.com/api/v1/dummy"
  clientId : "dummyxxx"
  clientSecret : "dummyxxx"
